---
kind: pipeline
type: kubernetes
name: linter

clone:
  disable: true

platform:
  os: linux

steps:
- name: clone
  image: git.cryptic.systems/volker.raschek/git:1.2.1

- name: markdown lint
  commands:
  - markdownlint *.md
  image: git.cryptic.systems/volker.raschek/markdownlint:0.34.0
  resources:
    limits:
      cpu: 150
      memory: 150M

- name: email-notification
  environment:
    SMTP_FROM_ADDRESS:
      from_secret: smtp_from_address
    SMTP_FROM_NAME:
      from_secret: smtp_from_name
    SMTP_HOST:
      from_secret: smtp_host
    SMTP_USERNAME:
      from_secret: smtp_username
    SMTP_PASSWORD:
      from_secret: smtp_password
  image: docker.io/volkerraschek/drone-email:0.1.1
  resources:
    limits:
      cpu: 150
      memory: 150M
  when:
    status:
    - changed
    - failure

trigger:
  event:
    exclude:
    - tag

---
kind: pipeline
type: docker
name: dry-run-amd64

clone:
  disable: true

platform:
  os: linux
  arch: amd64

steps:
- name: clone
  image: git.cryptic.systems/volker.raschek/git:1.2.1

- name: build
  image: docker.io/plugins/docker:20.10.9
  settings:
    auto_tag: false
    dry_run: true
    force_tag: true
    no_cache: true
    purge: true
    tags: latest-amd64
    repo: volkerraschek/yamllint
    username:
      from_secret: container_image_registry_user
    password:
      from_secret: container_image_registry_password

- name: email-notification
  environment:
    SMTP_FROM_ADDRESS:
      from_secret: smtp_from_address
    SMTP_FROM_NAME:
      from_secret: smtp_from_name
    SMTP_HOST:
      from_secret: smtp_host
    SMTP_USERNAME:
      from_secret: smtp_username
    SMTP_PASSWORD:
      from_secret: smtp_password
  image: docker.io/volkerraschek/drone-email:0.1.1
  when:
    status:
    - changed
    - failure

depends_on:
- linter

trigger:
  branch:
    exclude:
    - master
  event:
  - pull_request
  - push
  repo:
  - volker.raschek/yamllint-docker

---
kind: pipeline
type: docker
name: dry-run-arm-v7

clone:
  disable: true

platform:
  os: linux
  arch: arm

steps:
- name: clone
  image: git.cryptic.systems/volker.raschek/git:1.2.1

- name: build
  image: docker.io/plugins/docker:20.10.9
  settings:
    auto_tag: false
    dry_run: true
    force_tag: true
    no_cache: true
    purge: true
    tags: latest-arm-v7
    repo: volkerraschek/yamllint
    username:
      from_secret: container_image_registry_user
    password:
      from_secret: container_image_registry_password

- name: email-notification
  environment:
    SMTP_FROM_ADDRESS:
      from_secret: smtp_from_address
    SMTP_FROM_NAME:
      from_secret: smtp_from_name
    SMTP_HOST:
      from_secret: smtp_host
    SMTP_USERNAME:
      from_secret: smtp_username
    SMTP_PASSWORD:
      from_secret: smtp_password
  image: docker.io/volkerraschek/drone-email:0.1.1
  when:
    status:
    - changed
    - failure

depends_on:
- linter

trigger:
  branch:
    exclude:
    - master
  event:
  - pull_request
  - push
  repo:
  - volker.raschek/yamllint-docker

---
kind: pipeline
type: docker
name: dry-run-arm64-v8

clone:
  disable: true

platform:
  os: linux
  arch: arm64

steps:
- name: clone
  image: git.cryptic.systems/volker.raschek/git:1.2.1

- name: build
  image: docker.io/plugins/docker:20.10.9
  settings:
    auto_tag: false
    dry_run: true
    force_tag: true
    no_cache: true
    purge: true
    tags: latest-arm64-v8
    repo: volkerraschek/yamllint
    username:
      from_secret: container_image_registry_user
    password:
      from_secret: container_image_registry_password

- name: email-notification
  environment:
    SMTP_FROM_ADDRESS:
      from_secret: smtp_from_address
    SMTP_FROM_NAME:
      from_secret: smtp_from_name
    SMTP_HOST:
      from_secret: smtp_host
    SMTP_USERNAME:
      from_secret: smtp_username
    SMTP_PASSWORD:
      from_secret: smtp_password
  image: docker.io/volkerraschek/drone-email:0.1.1
  when:
    status:
    - changed
    - failure

depends_on:
- linter

trigger:
  branch:
    exclude:
    - master
  event:
  - pull_request
  - push
  repo:
  - volker.raschek/yamllint-docker

---
kind: pipeline
type: docker
name: latest-amd64

clone:
  disable: true

platform:
  os: linux
  arch: amd64

steps:
- name: clone
  image: git.cryptic.systems/volker.raschek/git:1.2.1

- name: build
  image: docker.io/plugins/docker:20.10.9
  settings:
    auto_tag: false
    force_tag: true
    no_cache: true
    purge: true
    tags: latest-amd64
    repo: volkerraschek/yamllint
    username:
      from_secret: container_image_registry_user
    password:
      from_secret: container_image_registry_password

- name: email-notification
  environment:
    SMTP_FROM_ADDRESS:
      from_secret: smtp_from_address
    SMTP_FROM_NAME:
      from_secret: smtp_from_name
    SMTP_HOST:
      from_secret: smtp_host
    SMTP_USERNAME:
      from_secret: smtp_username
    SMTP_PASSWORD:
      from_secret: smtp_password
  image: docker.io/volkerraschek/drone-email:0.1.1
  when:
    status:
    - changed
    - failure

depends_on:
- linter

trigger:
  branch:
  - master
  event:
  - cron
  - push
  repo:
  - volker.raschek/yamllint-docker

---
kind: pipeline
type: docker
name: latest-arm-v7

clone:
  disable: true

platform:
  os: linux
  arch: arm

steps:
- name: clone
  image: git.cryptic.systems/volker.raschek/git:1.2.1

- name: build
  image: docker.io/plugins/docker:20.10.9
  settings:
    auto_tag: false
    force_tag: true
    no_cache: true
    purge: true
    tags: latest-arm-v7
    repo: volkerraschek/yamllint
    username:
      from_secret: container_image_registry_user
    password:
      from_secret: container_image_registry_password

- name: email-notification
  environment:
    SMTP_FROM_ADDRESS:
      from_secret: smtp_from_address
    SMTP_FROM_NAME:
      from_secret: smtp_from_name
    SMTP_HOST:
      from_secret: smtp_host
    SMTP_USERNAME:
      from_secret: smtp_username
    SMTP_PASSWORD:
      from_secret: smtp_password
  image: docker.io/volkerraschek/drone-email:0.1.1
  when:
    status:
    - changed
    - failure

depends_on:
- linter

trigger:
  branch:
  - master
  event:
  - cron
  - push
  repo:
  - volker.raschek/yamllint-docker

---
kind: pipeline
type: docker
name: latest-arm64-v8

clone:
  disable: true

platform:
  os: linux
  arch: arm64

steps:
- name: clone
  image: git.cryptic.systems/volker.raschek/git:1.2.1

- name: build
  image: docker.io/plugins/docker:20.10.9
  settings:
    auto_tag: false
    force_tag: true
    no_cache: true
    purge: true
    tags: latest-arm64-v8
    repo: volkerraschek/yamllint
    username:
      from_secret: container_image_registry_user
    password:
      from_secret: container_image_registry_password

- name: email-notification
  environment:
    SMTP_FROM_ADDRESS:
      from_secret: smtp_from_address
    SMTP_FROM_NAME:
      from_secret: smtp_from_name
    SMTP_HOST:
      from_secret: smtp_host
    SMTP_USERNAME:
      from_secret: smtp_username
    SMTP_PASSWORD:
      from_secret: smtp_password
  image: docker.io/volkerraschek/drone-email:0.1.1
  when:
    status:
    - changed
    - failure

depends_on:
- linter

trigger:
  branch:
  - master
  event:
  - cron
  - push
  repo:
  - volker.raschek/yamllint-docker

---
kind: pipeline
type: kubernetes
name: latest-manifest

clone:
  disable: true

steps:
- name: clone
  image: git.cryptic.systems/volker.raschek/git:1.2.1

- name: build-manifest
  image: docker.io/plugins/manifest:latest
  settings:
    auto_tag: false
    ignore_missing: true
    spec: manifest.tmpl
    username:
      from_secret: container_image_registry_user
    password:
      from_secret: container_image_registry_password

- name: email-notification
  environment:
    SMTP_FROM_ADDRESS:
      from_secret: smtp_from_address
    SMTP_FROM_NAME:
      from_secret: smtp_from_name
    SMTP_HOST:
      from_secret: smtp_host
    SMTP_USERNAME:
      from_secret: smtp_username
    SMTP_PASSWORD:
      from_secret: smtp_password
  image: docker.io/volkerraschek/drone-email:0.1.1
  resources:
    limits:
      cpu: 150
      memory: 150M
  when:
    status:
    - changed
    - failure

depends_on:
- latest-amd64
- latest-arm-v7
- latest-arm64-v8

trigger:
  branch:
  - master
  event:
  - cron
  - push
  repo:
  - volker.raschek/yamllint-docker

---
kind: pipeline
type: docker
name: tagged-amd64

clone:
  disable: true

platform:
  os: linux
  arch: amd64

steps:
- name: clone
  image: git.cryptic.systems/volker.raschek/git:1.2.1

- name: build
  image: docker.io/plugins/docker:20.10.9
  settings:
    auto_tag: true
    auto_tag_suffix: amd64
    force_tag: true
    no_cache: true
    purge: true
    repo: volkerraschek/yamllint
    username:
      from_secret: container_image_registry_user
    password:
      from_secret: container_image_registry_password
    build_args:
    - YAMLLINT_VERSION=${DRONE_TAG}

- name: email-notification
  environment:
    SMTP_FROM_ADDRESS:
      from_secret: smtp_from_address
    SMTP_FROM_NAME:
      from_secret: smtp_from_name
    SMTP_HOST:
      from_secret: smtp_host
    SMTP_USERNAME:
      from_secret: smtp_username
    SMTP_PASSWORD:
      from_secret: smtp_password
  image: docker.io/volkerraschek/drone-email:0.1.1
  when:
    status:
    - changed
    - failure

trigger:
  event:
  - tag
  repo:
  - volker.raschek/yamllint-docker

---
kind: pipeline
type: docker
name: tagged-arm-v7

clone:
  disable: true

platform:
  os: linux
  arch: arm

steps:
- name: clone
  image: git.cryptic.systems/volker.raschek/git:1.2.1

- name: build
  image: docker.io/plugins/docker:20.10.9
  settings:
    auto_tag: true
    auto_tag_suffix: arm-v7
    force_tag: true
    no_cache: true
    purge: true
    repo: volkerraschek/yamllint
    username:
      from_secret: container_image_registry_user
    password:
      from_secret: container_image_registry_password
    build_args:
    - YAMLLINT_VERSION=${DRONE_TAG}

- name: email-notification
  environment:
    SMTP_FROM_ADDRESS:
      from_secret: smtp_from_address
    SMTP_FROM_NAME:
      from_secret: smtp_from_name
    SMTP_HOST:
      from_secret: smtp_host
    SMTP_USERNAME:
      from_secret: smtp_username
    SMTP_PASSWORD:
      from_secret: smtp_password
  image: docker.io/volkerraschek/drone-email:0.1.1
  when:
    status:
    - changed
    - failure

trigger:
  event:
  - tag
  repo:
  - volker.raschek/yamllint-docker

---
kind: pipeline
type: docker
name: tagged-arm64-v8

clone:
  disable: true

platform:
  os: linux
  arch: arm64

steps:
- name: clone
  image: git.cryptic.systems/volker.raschek/git:1.2.1

- name: build
  image: docker.io/plugins/docker:20.10.9
  settings:
    auto_tag: true
    auto_tag_suffix: arm64-v8
    force_tag: true
    no_cache: true
    purge: true
    repo: volkerraschek/yamllint
    username:
      from_secret: container_image_registry_user
    password:
      from_secret: container_image_registry_password
    build_args:
    - YAMLLINT_VERSION=${DRONE_TAG}

- name: email-notification
  environment:
    SMTP_FROM_ADDRESS:
      from_secret: smtp_from_address
    SMTP_FROM_NAME:
      from_secret: smtp_from_name
    SMTP_HOST:
      from_secret: smtp_host
    SMTP_USERNAME:
      from_secret: smtp_username
    SMTP_PASSWORD:
      from_secret: smtp_password
  image: docker.io/volkerraschek/drone-email:0.1.1
  when:
    status:
    - changed
    - failure

trigger:
  event:
  - tag
  repo:
  - volker.raschek/yamllint-docker

---
kind: pipeline
type: kubernetes
name: tagged-manifest

clone:
  disable: true

steps:
- name: clone
  image: git.cryptic.systems/volker.raschek/git:1.2.1

- name: build-manifest
  image: docker.io/plugins/manifest:latest
  settings:
    auto_tag: true
    ignore_missing: true
    spec: manifest.tmpl
    username:
      from_secret: container_image_registry_user
    password:
      from_secret: container_image_registry_password

- name: email-notification
  environment:
    SMTP_FROM_ADDRESS:
      from_secret: smtp_from_address
    SMTP_FROM_NAME:
      from_secret: smtp_from_name
    SMTP_HOST:
      from_secret: smtp_host
    SMTP_USERNAME:
      from_secret: smtp_username
    SMTP_PASSWORD:
      from_secret: smtp_password
  image: docker.io/volkerraschek/drone-email:0.1.1
  resources:
    limits:
      cpu: 150
      memory: 150M
  when:
    status:
    - changed
    - failure

depends_on:
- tagged-amd64
- tagged-arm-v7
- tagged-arm64-v8

trigger:
  event:
  - tag
  repo:
  - volker.raschek/yamllint-docker
