name: Build

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
  push:
    branches:
    - master
  workflow_dispatch: {}

jobs:
  build-arm64:
    runs-on: ubuntu-latest-arm64
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: docker/setup-qemu-action@v3.6.0
      - uses: docker/setup-buildx-action@v3.10.0

      - name: Build image
        run: |
          TAG=latest

          docker buildx build \
            --platform linux/arm64 \
            --file Dockerfile \
            --provenance false \
            --tag git.cryptic.systems/volker.raschek/yamllint:${TAG}-arm64 \
            .

  build-amd64:
    runs-on: ubuntu-latest-amd64
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: docker/setup-qemu-action@v3.6.0
      - uses: docker/setup-buildx-action@v3.10.0

      - name: Build image
        run: |
          TAG=latest

          docker buildx build \
            --platform linux/amd64 \
            --file Dockerfile \
            --provenance false \
            --tag git.cryptic.systems/volker.raschek/yamllint:${TAG}-amd64 \
            .
