name: 'Lint Markdown files'

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
  push:
    branches:
    - master
  workflow_dispatch: {}

jobs:
  markdown-lint:
    runs-on:
    - ubuntu-latest
    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
    - uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd # v23.2.0
      with:
        globs: '**/*.md'
