name: Update Docker Hub Description

on:
  push:
    branches:
    - master
    paths:
    - README.md
  workflow_dispatch: {}

jobs:
  update-description-on-hub-docker-io:
    runs-on:
    - ubuntu-latest
    steps:
    - uses: actions/checkout@v5.0.0
    - uses: peter-evans/dockerhub-description@v4.0.2
      with:
        username: ${{ secrets.DOCKER_IO_USERNAME }}
        password: ${{ secrets.DOCKER_IO_PASSWORD }}
        repository: volkerraschek/yamllint
        readme-filepath: README.md